library(usethis)
library(devtools)
library(cisSceQTL)
install_github("XFWuCN/cisSceQTL", force = TRUE)
devtools::install_github("XFWuCN/cisSceQTL")
chooseCRANmirror(graphics = FALSE)
options(repos = c(CRAN = "https://cloud.r-project.org"))
remotes::install_github("XFWuCN/cisSceQTL", build = FALSE,force = TRUE)
install.packages("meme")
library(meme)
install.packages("installr")
require(installr)
updateR()
options(repos = c(CRAN = "https://mirrors.ustc.edu.cn/CRAN/"))
options(repos = c(CRAN = "https://mirrors.ustc.edu.cn/CRAN/"))
remotes::install_github("XFWuCN/cisSceQTL", build = FALSE, force = TRUE)
getOption("repos")
